name: Improver7
on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  coverage_test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.8.0
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        message: "testPR recreate"
